#!/usr/bin/env python
# coding: utf-8

# In[6]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
get_ipython().run_line_magic('matplotlib', 'inline')
import warnings
warnings.filterwarnings('ignore')


# In[77]:


df = pd.read_csv('MANI1.csv',sep=';',decimal=',')
df.head()


# In[78]:


X = df.drop('default.payment.next.month',axis=1)
Y = df['default.payment.next.month']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 1)


# In[79]:


from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 100,criterion = 'entropy',random_state = 0)
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)


# In[80]:


Instanzen = pd.read_csv('Instanzen_MANI1.csv',sep=';',decimal=',')
Instanzen = Instanzen.drop('ID',axis=1)
X_Instanzen = Instanzen.drop('default.payment.next.month',axis=1)
Y_Instanzen = Instanzen['default.payment.next.month']


# In[81]:


y_train.replace([0,1],['No default','Default'],inplace=True)
y_test.replace([0,1],['No default','Default'],inplace=True)


# In[82]:


import lime
from lime.lime_tabular import LimeTabularExplainer
explainer= LimeTabularExplainer(training_data=np.array(X_train),
                                mode='classification', 
                                feature_names=list(X_train.columns),
                                training_labels=np.array(y_train),
                                class_names=['No default','Default'],
                                random_state=12)


# In[1]:


Erklärungen = pd.DataFrame(columns=['Variable','Wichtigkeit'])

for i in range(10):

    exp = explainer.explain_instance(X_Instanzen.iloc[i], rfc.predict_proba,num_features=21)
    Werte = pd.DataFrame(exp.as_list(),columns=['Variable','Wichtigkeit'])
    Erklärungen = Erklärungen.append({'Variable' : 'MANI1' , 'Wichtigkeit' : i+1} , ignore_index=True)
    Erklärungen = Erklärungen.append(Werte)
    
Erklärungen


# In[ ]:


Erklärungen.to_csv('Erklärungen_LIME_MANI1.csv')


# In[ ]:




